src/Entity/Vaccination.php
<?php

namespace App\Entity;

use App\Repository\VaccinationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VaccinationRepository::class)
 */
class Vaccination
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Patient::class, inversedBy="vaccinations")
     */
    private $patient;

    /**
     * @ORM\ManyToOne(targetEntity=Vaccin::class)
     */
    private $vaccin;

    /**
     * @ORM\ManyToOne(targetEntity=CentreVaccination::class, inversedBy="vaccinations")
     */
    private $centreVaccination;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $statut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_vaccination;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(?Patient $patient): self
    {
        $this->patient = $patient;

        return $this;
    }

    public function getVaccin(): ?Vaccin
    {
        return $this->vaccin;
    }

    public function setVaccin(?Vaccin $vaccin): self
    {
        $this->vaccin = $vaccin;

        return $this;
    }

    public function getCentreVaccination(): ?CentreVaccination
    {
        return $this->centreVaccination;
    }

    public function setCentreVaccination(?CentreVaccination $centreVaccination): self
    {
        $this->centreVaccination = $centreVaccination;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getDateVaccination(): ?\DateTimeInterface
    {
        return $this->date_vaccination;
    }

    public function setDateVaccination(\DateTimeInterface $date_vaccination): self
    {
        $this->date_vaccination = $date_vaccination;

        return $this;
    }
}

src/Form/VaccinationType.php
<?php

namespace App\Form;

use App\Entity\Vaccination;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VaccinationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('statut')
            ->add('date_vaccination')
            ->add('patient',null,[
                'disabled' => true,
            ])
            ->add('vaccin')
            ->add('centreVaccination');
        
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Vaccination::class,
        ]);
    }
}

src/Controller/VaccinationController.php
<?php

namespace App\Controller;

use App\Entity\Patient;
use App\Repository\PatientRepository;
use App\Form\PatientType;
use App\Entity\CentreVaccination;
use App\Repository\CentreVaccinationRepository;
use App\Form\CentreVaccinationType;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;


use App\Entity\Vaccination;
use App\Form\VaccinationType;
use App\Repository\VaccinationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/vaccination")
 */
class VaccinationController extends AbstractController
{
    /**
     * @Route("/", name="vaccination_index", methods={"GET"})
     */
    public function index(VaccinationRepository $vaccinationRepository): Response
    {
        return $this->render('vaccination/index.html.twig', [
            'vaccinations' => $vaccinationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="vaccination_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $vaccination = new Vaccination();
        $form = $this->createForm(VaccinationType::class, $vaccination);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($vaccination);
            $entityManager->flush();

            return $this->redirectToRoute('vaccination_index');
        }

        return $this->render('vaccination/new.html.twig', [
            'vaccination' => $vaccination,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="vaccination_show", methods={"GET"})
     */
    public function show(Vaccination $vaccination): Response
    {
        return $this->render('vaccination/show.html.twig', [
            'vaccination' => $vaccination,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="vaccination_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Vaccination $vaccination): Response
    {
        $form = $this->createForm(VaccinationType::class, $vaccination);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('vaccination_index');
        }

        return $this->render('vaccination/edit.html.twig', [
            'vaccination' => $vaccination,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="vaccination_delete", methods={"POST"})
     */
    public function delete(Request $request, Vaccination $vaccination): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vaccination->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($vaccination);
            $entityManager->flush();
        }

        return $this->redirectToRoute('vaccination_index');
    }

        /**
     * @Route("/{id}/newPatientVacc", name="vaccination_new_patient", methods={"GET","POST"})
     */

    public function newPatientVacc(Request $request, Patient $patient): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $vaccination = new Vaccination();
        $form = $this->createForm(VaccinationType::class, $vaccination);
        //$p= $entityManager->find('App\Entity\Patient','id');

        $vaccination->setPatient($patient);
        $form->get('patient')->setData($vaccination->getPatient());
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($vaccination);
            $entityManager->flush();

            return $this->redirectToRoute('vaccination_index');
        }

        return $this->render('vaccination/new.html.twig', [
            'vaccination' => $vaccination,
            'form' => $form->createView(),
        ]);
    }

     /**
     * @Route("/{id}/PatientVaccinations", name="patient_vaccinations", methods={"GET","POST"})
     */

    public function PatientVacc(Request $request,VaccinationRepository $vaccinationRepository, Patient $patient): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $vaccination = new Vaccination();
        $form = $this->createForm(VaccinationType::class, $vaccination);
        //$p= $entityManager->find('App\Entity\Patient','id');

        $vaccination->setPatient($patient);
        $form->get('patient')->setData($vaccination->getPatient());
        $form->handleRequest($request);

        return $this->render('vaccination/index.html.twig', [
            'vaccinations' => $patient->getVaccinations(),
        ]);
    }

    /**
     * @Route("/{id}/CentreVaccinations", name="centre_vaccinations", methods={"GET","POST"})
     */

    public function centreVacc(Request $request,VaccinationRepository $vaccinationRepository, CentreVaccination $centreVaccination): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $vaccination = new Vaccination();
        $form = $this->createForm(VaccinationType::class, $vaccination);
        $vaccination->setCentreVaccination($centreVaccination);
        $form->get('centreVaccination')->setData($vaccination->getCentreVaccination());
        $form->handleRequest($request);

        return $this->render('vaccination/index.html.twig', [
            'vaccinations' => $centreVaccination->getVaccinations(),
        ]);
    }
}

templates/vaccination/_delete_form.html.twig
<form method="post" action="{{ path('vaccination_delete', {'id': vaccination.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vaccination.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/vaccination/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
<div class="form-group">
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary btn-lg">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}
</div>

templates/vaccination/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Vaccination{% endblock %}

{% block body %}
<div class="container-fluid">
    <h1>Mettre à jour la vaccination</h1>
</div>
<div class="container-fluid">
    {{ include('vaccination/_form.html.twig', {'button_label': 'Update'}) }}
    <a href="{{ path('vaccination_index') }}">Retourner</a>

</div>
  
{% endblock %}

templates/vaccination/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vaccination index{% endblock %}

{% block body %}

<div class="container-fluid">
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Liste des vaccinations</h1>
    
</div>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Statut</th>
                <th>Date_vaccination</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for vaccination in vaccinations %}
            <tr>
                <td>{{ vaccination.id }}</td>
                <td>{{ vaccination.statut }}</td>
                <td>{{ vaccination.dateVaccination ? vaccination.dateVaccination|date('Y-m-d') : '' }}</td>
                <td>

                    <a  type="button" class="btn btn-primary" href="{{ path('vaccination_show', {'id': vaccination.id}) }}">Voir</a>
                    <a  type="button" class="btn btn-secondary" href="{{ path('vaccination_edit', {'id': vaccination.id}) }}">Mettre à jour</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/vaccination/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Vaccination{% endblock %}

{% block body %}

    <div class="container-fluid">
        
        <h1>Ajouter une vaccination</h1>
    </div>
    <div class="container-fluid">
    {{ include('vaccination/_form.html.twig') }}

    <a href="{{ path('vaccination_index') }}">back to list</a>
    
    </div>
{% endblock %}

templates/vaccination/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vaccination{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Vaccination </h1>
        
   </div>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vaccination.id }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ vaccination.statut }}</td>
            </tr>
            <tr>
                <th>Patient</th>
                <td>{{ vaccination.patient }}</td>
            </tr> 
            <tr>
                <th>Nom du vaccin</th>
                <td>{{ vaccination.vaccin }}</td>
            </tr>          
            <tr>
                <th>Centre de vaccination</th>
                <td>{{ vaccination.centreVaccination }}</td>
            </tr>
            <tr>
                <th>Date_vaccination</th>
                <td>{{ vaccination.dateVaccination ? vaccination.dateVaccination|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a  type="button" class="btn btn-secondary" href="{{ path('vaccination_edit', {'id': vaccination.id}) }}">Mettre à jour</a>
    <a  type="button" class="btn btn-secondary" href="{{ path('vaccination_index') }}">Retourner a la liste</a>

    {{ include('vaccination/_delete_form.html.twig') }}
</div>
{% endblock %}