src/Entity/Vaccin.php
<?php

namespace App\Entity;

use App\Repository\VaccinRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VaccinRepository::class)
 */
class Vaccin
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_vaccin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomVaccin(): ?string
    {
        return $this->nom_vaccin;
    }

    public function setNomVaccin(string $nom_vaccin): self
    {
        $this->nom_vaccin = $nom_vaccin;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function __toString(): String
    {
        return $this->nom_vaccin;
    }

    
}

src/Form/VaccinType.php
<?php

namespace App\Form;

use App\Entity\Vaccin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class VaccinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_vaccin')
            ->add('description')
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Vaccin::class,
        ]);
    }
}

src/Controller/VaccinController.php
<?php

namespace App\Controller;

use App\Entity\Vaccin;
use App\Form\VaccinType;
use App\Repository\VaccinRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/vaccin")
 */
class VaccinController extends AbstractController
{
    /**
     * @Route("/", name="vaccin_index", methods={"GET"})
     */
    public function index(VaccinRepository $vaccinRepository): Response
    {
        return $this->render('vaccin/index.html.twig', [
            'vaccins' => $vaccinRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="vaccin_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $vaccin = new Vaccin();
        $form = $this->createForm(VaccinType::class, $vaccin);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($vaccin);
            $entityManager->flush();

            return $this->redirectToRoute('vaccin_index');
        }

        return $this->render('vaccin/new.html.twig', [
            'vaccin' => $vaccin,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="vaccin_show", methods={"GET"})
     */
    public function show(Vaccin $vaccin): Response
    {
        return $this->render('vaccin/show.html.twig', [
            'vaccin' => $vaccin,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="vaccin_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Vaccin $vaccin): Response
    {
        $form = $this->createForm(VaccinType::class, $vaccin);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('vaccin_index');
        }

        return $this->render('vaccin/edit.html.twig', [
            'vaccin' => $vaccin,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="vaccin_delete", methods={"POST"})
     */
    public function delete(Request $request, Vaccin $vaccin): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vaccin->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($vaccin);
            $entityManager->flush();
        }

        return $this->redirectToRoute('vaccin_index');
    }
}

templates/vaccin/_delete_form.html.twig
<p>
<form method="post" action="{{ path('vaccin_delete', {'id': vaccin.id}) }}" onsubmit="return confirm('Etes vous sur de vouloir supprimer ce patient?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vaccin.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>
</p>

templates/vaccin/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary btn-lg">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/vaccin/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Vaccin{% endblock %}

{% block body %}
<div class="container-fluid">
    <h1>Mettre à jour un vaccin</h1>
</div>
<div class="container-fluid">
    {{ include('vaccin/_form.html.twig', {'button_label': 'Update'}) }}
</div>
    
{% endblock %}

templates/vaccin/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vaccin index{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Liste des vaccins</h1>
        
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_vaccin</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for vaccin in vaccins %}
            <tr>
                <td>{{ vaccin.id }}</td>
                <td>{{ vaccin.nomVaccin }}</td>
                <td>{{ vaccin.description }}</td>
                <td>
                    <a type="button" class="btn btn-primary" href="{{ path('vaccin_show', {'id': vaccin.id}) }}">Voir</a>
                    <a type="button" class="btn btn-secondary" href="{{ path('vaccin_edit', {'id': vaccin.id}) }}">Mettre à jour</a>
                    
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('vaccin_new') }}"  type="button" class="btn btn-success">Ajouter un nouveau vaccin</a>
{% endblock %}

templates/vaccin/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Vaccin{% endblock %}

{% block body %}
<div class="container-fluid">
    
    <h1>Ajouter un nouveau vaccin</h1>
</div>
<div class="container-fluid">
    {{ include('vaccin/_form.html.twig') }}
    
</div>
 
{% endblock %}

templates/vaccin/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vaccin{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Informations sur le vaccin </h1>
        
   </div>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vaccin.id }}</td>
            </tr>
            <tr>
                <th>Nom_vaccin</th>
                <td>{{ vaccin.nomVaccin }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ vaccin.description }}</td>
            </tr>
        </tbody>
    </table>
    <a class="btn btn-secondary" href="{{ path('vaccin_edit', {'id': vaccin.id}) }}">Mettre à jour</a>

    {{ include('vaccin/_delete_form.html.twig') }}
{% endblock %}