src/Entity/CentreVaccination.php
<?php

namespace App\Entity;

use App\Repository\CentreVaccinationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CentreVaccinationRepository::class)
 */
class CentreVaccination
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_centre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nombre_vaccin_disponible;

    /**
     * @ORM\OneToMany(targetEntity=Vaccination::class, mappedBy="centreVaccination")
     */
    private $vaccinations;

    public function __construct()
    {
        $this->vaccinations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCentre(): ?string
    {
        return $this->nom_centre;
    }

    public function setNomCentre(string $nom_centre): self
    {
        $this->nom_centre = $nom_centre;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getNombreVaccinDisponible(): ?int
    {
        return $this->nombre_vaccin_disponible;
    }

    public function setNombreVaccinDisponible(?int $nombre_vaccin_disponible): self
    {
        $this->nombre_vaccin_disponible = $nombre_vaccin_disponible;

        return $this;
    }

    /**
     * @return Collection|Vaccination[]
     */
    public function getVaccinations(): Collection
    {
        return $this->vaccinations;
    }

    public function addVaccination(Vaccination $vaccination): self
    {
        if (!$this->vaccinations->contains($vaccination)) {
            $this->vaccinations[] = $vaccination;
            $vaccination->setCentreVaccination($this);
        }

        return $this;
    }

    public function removeVaccination(Vaccination $vaccination): self
    {
        if ($this->vaccinations->removeElement($vaccination)) {
            // set the owning side to null (unless already changed)
            if ($vaccination->getCentreVaccination() === $this) {
                $vaccination->setCentreVaccination(null);
            }
        }

        return $this;
    }

    public function __toString(): String
    {
        return $this->nom_centre;
    }
}

src/Form/CentreVaccinationType.php
<?php

namespace App\Form;

use App\Entity\CentreVaccination;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CentreVaccinationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_centre')
            ->add('adresse')
            ->add('ville')
            ->add('nombre_vaccin_disponible')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CentreVaccination::class,
        ]);
    }
}

src/Controller/CentreVaccinationController.php
<?php

namespace App\Controller;

use App\Entity\CentreVaccination;
use App\Form\CentreVaccinationType;
use App\Repository\CentreVaccinationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

//("/centre/vaccination")

/**
 * @Route("/centreVaccination")
 */
class CentreVaccinationController extends AbstractController
{
    /**
     * @Route("/", name="centre_vaccination_index", methods={"GET"})
     */
    public function index(CentreVaccinationRepository $centreVaccinationRepository): Response
    {
        return $this->render('centre_vaccination/index.html.twig', [
            'centre_vaccinations' => $centreVaccinationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="centre_vaccination_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $centreVaccination = new CentreVaccination();
        $form = $this->createForm(CentreVaccinationType::class, $centreVaccination);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($centreVaccination);
            $entityManager->flush();

            return $this->redirectToRoute('centre_vaccination_index');
        }

        return $this->render('centre_vaccination/new.html.twig', [
            'centre_vaccination' => $centreVaccination,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="centre_vaccination_show", methods={"GET"})
     */
    public function show(CentreVaccination $centreVaccination): Response
    {
        return $this->render('centre_vaccination/show.html.twig', [
            'centre_vaccination' => $centreVaccination,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="centre_vaccination_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, CentreVaccination $centreVaccination): Response
    {
        $form = $this->createForm(CentreVaccinationType::class, $centreVaccination);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('centre_vaccination_index');
        }

        return $this->render('centre_vaccination/edit.html.twig', [
            'centre_vaccination' => $centreVaccination,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="centre_vaccination_delete", methods={"POST"})
     */
    public function delete(Request $request, CentreVaccination $centreVaccination): Response
    {
        if ($this->isCsrfTokenValid('delete'.$centreVaccination->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($centreVaccination);
            $entityManager->flush();
        }

        return $this->redirectToRoute('centre_vaccination_index');
    }
}

templates/centre_vaccination/_delete_form.html.twig
<form method="post" action="{{ path('centre_vaccination_delete', {'id': centre_vaccination.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ centre_vaccination.id) }}">
    <button class="btn">Delete</button>
</form>

templates/centre_vaccination/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
<div class="form-group">
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary btn-lg">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}
</div>

templates/centre_vaccination/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit CentreVaccination{% endblock %}


{% block body %}
<div class="container-fluid">
    <h1>Mettre à jour ce centre de vaccination</h1>
</div>
<div class="container-fluid">
    {{ include('centre_vaccination/_form.html.twig', {'button_label': 'Update'}) }}
    <a href="{{ path('centre_vaccination_index') }}">Retourner</a>

</div>
  
{% endblock %}

templates/centre_vaccination/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CentreVaccination index{% endblock %}

{% block body %}

<div class="container-fluid">
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Liste des centres de vaccination</h1>
    
</div>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_centre</th>
                <th>Adresse</th>
                <th>Ville</th>
                <th>Nombre_vaccin_disponible</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for centre_vaccination in centre_vaccinations %}
            <tr>
                <td>{{ centre_vaccination.id }}</td>
                <td>{{ centre_vaccination.nomCentre }}</td>
                <td>{{ centre_vaccination.adresse }}</td>
                <td>{{ centre_vaccination.ville }}</td>
                <td>{{ centre_vaccination.nombreVaccinDisponible }}</td>
                <td>

                    <a  type="button" class="btn btn-primary" href="{{ path('centre_vaccination_show', {'id': centre_vaccination.id}) }}">Voir</a>
                    <a  type="button" class="btn btn-secondary" href="{{ path('centre_vaccination_edit', {'id': centre_vaccination.id}) }}">Mettre à jour</a>
                 <!--   {{ include('centre_vaccination/_delete_form.html.twig') }} -->
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('centre_vaccination_new') }}" type="button" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i>Ajouter un nouveau centre</a>
</div>
{% endblock %}

templates/centre_vaccination/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New CentreVaccination{% endblock %}

{% block body %}

    <div class="container-fluid">
        
        <h1>Ajouter un centre de vaccination</h1>
    </div>
    <div class="container-fluid">
        {{ include('centre_vaccination/_form.html.twig') }}
    
    </div>
{% endblock %}

templates/centre_vaccination/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}CentreVaccination{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Details du centre de vaccination </h1>
        
    </div>    

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ centre_vaccination.id }}</td>
            </tr>
            <tr>
                <th>Nom_centre</th>
                <td>{{ centre_vaccination.nomCentre }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ centre_vaccination.adresse }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ centre_vaccination.ville }}</td>
            </tr>
            <tr>
                <th>Nombre_vaccin_disponible</th>
                <td>{{ centre_vaccination.nombreVaccinDisponible }}</td>
            </tr>
        </tbody>
    </table>
    <a  type="button" class="btn btn-success" href="{{ path('centre_vaccinations', {'id': centre_vaccination.id}) }}">Vaccinations</a>
    <a  type="button" class="btn btn-secondary" href="{{ path('centre_vaccination_edit', {'id': centre_vaccination.id}) }}">Mettre à jour</a>
    <a  type="button" class="btn btn-secondary" href="{{ path('centre_vaccination_index') }}">Retourner a la liste</a>

   <!-- {{ include('centre_vaccination/_delete_form.html.twig') }} -->
</div>
{% endblock %}